### ISSUE TITLE
Setup File "system cannot find the file specified"

### ISSUE THREAD

**Issue by codemonster33** [ObjRand/ASMBLR#1]
###  **You changed the name in the newest release to ASMBLR-1.0.exe and forgot to change it in the batch file** :
When i run the setup file it gives me the error, "The system cannot find the file specified" on the command :
                 **"move ASMBLR.exe C:\ASMBLR"** on line 3
### Directory : 
![image](https://github.com/ObjRand/ASMBLR/assets/79758393/756c4a9f-172f-4a31-80d5-ade7c4fa89dd)

**Comment by ObjRand** [comment]
yeah I know about this, i haven't maintained the installation process in a while, it'll be fixed :P
